### ISSUE TITLE
File-generator

### ISSUE THREAD

**Issue by EduardVavrynchuk** [EduardVavrinchuk/TokenAnalysis#2]
During execution this ticket it is necessary to create classes that will be generating .xls files with data from MySQL DB.

**Comment by EduardVavrinchuk** [comment]
commit - Created xls file generator

**Comment by EduardVavrynchuk** [comment]
commit [Created xls file generator](https://github.com/EduardVavrinchuk/TokenAnalysis/commit/7134732fbb7354adcdbd80827e513e7b446053fd)
